import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import crypto from 'node:crypto';
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'lucio-dbgca-'));
process.env.LUCIO_DATA_DIR = tmp; process.env.BUILDER_RUNTIME_ENABLED = 'true';
const { createApp } = await import('../server/index.js');
const { db } = await import('../server/db.js');
const app = createApp();
const server = await new Promise((r) => { const s = app.listen(0, () => r(s)); });
const base = `http://127.0.0.1:${server.address().port}`;
let cookie = '';
async function call(m, p, b) {
  const res = await fetch(base + p, { method: m, headers: { 'Content-Type': 'application/json', ...(cookie ? { Cookie: cookie } : {}) }, body: b === undefined ? undefined : JSON.stringify(b) });
  const sc = res.headers.get('set-cookie'); if (sc) cookie = sc.split(';')[0];
  return { status: res.status, json: await res.json().catch(() => null) };
}
const reg = await call('POST', '/api/auth/register', { email: 'o@ca.test', name: 'O', password: 'password123', orgName: 'C' });
const orgId = reg.json.user.orgId, userId = reg.json.user.id;
const proj = await call('POST', '/api/nexus/projects', { name: 'T', brief: { industry: 'Locksmith' } });
const pid = proj.json.project.id;
await call('POST', `/api/nexus/projects/${pid}/runs`, { intent: 'A website for a locksmith called Iron Key' });
const dir = fs.mkdtempSync(path.join(tmp, 'ws-'));
fs.writeFileSync(path.join(dir, 'README.md'), 'round two readme\n');
fs.writeFileSync(path.join(dir, 'gallery.css'), '.gallery { display: grid; }\n');
fs.writeFileSync(path.join(dir, 'CONTEXT.md'), 'ctx');
const id = crypto.randomUUID();
db.prepare(`INSERT INTO claw_jobs (id, org_id, project_id, user_id, prompt, status, workspace_dir, transcript_json, created_at) VALUES (?,?,?,?,?, 'completed', ?, '[]', datetime('now'))`).run(id, orgId, pid, userId, 't', dir);
const out = await call('GET', `/api/claw/jobs/${id}/output`);
console.log('output:', out.status, JSON.stringify(out.json.files?.map((f) => ({ p: f.path, a: f.action }))));
const ap = await call('POST', `/api/claw/jobs/${id}/apply`, {});
console.log('apply:', ap.status, JSON.stringify(ap.json).slice(0, 300));
server.close(); process.exit(0);
